### ISSUE TITLE
simplify code

### ISSUE THREAD

**Issue by ggrothendieck** [mgirlich/tibblify#16]
Is there a way to get rid of the map_dfr in the code here and do it all in one tibblify:

https://stackoverflow.com/questions/65476652/convert-nested-list-to-dataframe-extract-only-specific-elements-of-interest/65477521#65477521

**Comment by mgirlich** [comment]
It is almost possible but not quite. First you need to use the first element of `my_data_object` to get the desired tibble. Then you have to `cbind()` the names to the tibble. But I'll think about adding a parameter `names_to` to `tibblify()` so that one doesn't have to do the `cbind()`. The resulting code is then as follows

``` r
library(purrr)
library(tibblify)

spec <-  lcols(
  lcol_chr("type"),
  lcol_chr("originType"),
  lcol_chr("title")
)

cbind(
  var_name = names(my_data_object[[1]]),
  tibblify(my_data_object[[1]], spec)
)
#>        var_name    type originType                               title
#> 1           age numeric     slider                   what is your age?
#> 2     med_field  string     choice     what medical branch are you at?
#> 3 covid_vaccine  string     choice when do you plan to get vaccinated?
```

<sup>Created on 2021-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
