### ISSUE TITLE
tib_col()

### ISSUE THREAD

**Issue by krlmlr** [mgirlich/tibblify#66]
New specification for a column-major data structure (and implicitly also for a data frame).

I suspect this might render redundant some code paths in the C++ implementation.

**Comment by mgirlich** [comment]
Instead of adding `tib_col()` I think this should be an argument `input_form = "colmajor"`. The question is whether it makes sense to allow colmajor and rowmajor input forms in one input. If we allow mixing them, then something funny happens

``` r
# outer - colmajor
# inner - colmajor
col_col <- list(
  scalar = 1:3,
  row = list(
    scalar = 4:6,
    vector = list(1, 2:3, NULL)
  )
)

# outer - colmajor
# inner - rowmajor
col_row <- list(
  scalar = 1:3,
  row = list(
    list(scalar = 4, vector = 1),
    list(scalar = 5, vector = 2:3),
    list(scalar = 6, vector = NULL)
  )
)

# outer - rowmajor
# inner - there is only one input form
row_x <- list(
  list(scalar = 1, row = list(scalar = 4, vector = 1)),
  list(scalar = 2, row = list(scalar = 5, vector = 2:3)),
  list(scalar = 3, row = list(scalar = 6, vector = NULL))
)

str(col_col)
#> List of 2
#>  $ scalar: int [1:3] 1 2 3
#>  $ row   :List of 2
#>   ..$ scalar: int [1:3] 4 5 6
#>   ..$ vector:List of 3
#>   .. ..$ : num 1
#>   .. ..$ : int [1:2] 2 3
#>   .. ..$ : NULL
str(col_row)
#> List of 2
#>  $ scalar: int [1:3] 1 2 3
#>  $ row   :List of 3
#>   ..$ :List of 2
#>   .. ..$ scalar: num 4
#>   .. ..$ vector: num 1
#>   ..$ :List of 2
#>   .. ..$ scalar: num 5
#>   .. ..$ vector: int [1:2] 2 3
#>   ..$ :List of 2
#>   .. ..$ scalar: num 6
#>   .. ..$ vector: NULL
str(row_x)
#> List of 3
#>  $ :List of 2
#>   ..$ scalar: num 1
#>   ..$ row   :List of 2
#>   .. ..$ scalar: num 4
#>   .. ..$ vector: num 1
#>  $ :List of 2
#>   ..$ scalar: num 2
#>   ..$ row   :List of 2
#>   .. ..$ scalar: num 5
#>   .. ..$ vector: int [1:2] 2 3
#>  $ :List of 2
#>   ..$ scalar: num 3
#>   ..$ row   :List of 2
#>   .. ..$ scalar: num 6
#>   .. ..$ vector: NULL
```

<sup>Created on 2022-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So, if it is not allowed to mix input forms then:

* only `spec_*()` needs an argument `input_form = c("rowmajor", "colmajor")`. The `tib_*()` interface stays a bit cleaner.
* Less code paths.
* The user could still parse this by using `tibblify()` twice: `spec_df(tib_variant("row"), input_form = "colmajor")` followed by `spec_df(tib_row("row"), input_form = "rowmajor")`. But it is a bit confusing.

It it is allowed to mix input forms then:

* `spec_*()`, `tib_row()`, and `tib_df()` require the argument `input_form`.
* The `input_form` argument of `tib_row()` is meaningless if it is inside a `rowmajor` structure.
* More code paths.
* The user can parse this in a single run.
* This form cannot really be generated by `jsonlite::toJSON()`

A third possiblity would be to not add `input_form` to `tib_row()` so that the second case is not possible.

@krlmlr Can you think of a case where you have encountered or might encounter mixed input forms? If you don't see big advantages of allowing to mix input forms I would prefer to only add the argument to `spec_*()`. What do you think?

**Comment by krlmlr** [comment]
Could mixed forms happen if a database returns a table with a JSON column? We're working on nesting into JSON in dm, the inputs would look like:

``` r
library(tibble)

tibble(a = 1, b = '{"c": 2}')
#> # A tibble: 1 × 2
#>       a b           
#>   <dbl> <chr>       
#> 1     1 "{\"c\": 2}"
tibble(a = 1, b = '[{"c": 2}, {"c": 3}]')
#> # A tibble: 1 × 2
#>       a b                         
#>   <dbl> <chr>                     
#> 1     1 "[{\"c\": 2}, {\"c\": 3}]"
```

<sup>Created on 2022-07-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Can tibblify help deal with those? The final desired result would be a packed or nested data frame, respectively.

**Comment by mgirlich** [comment]
A data frame would not need the input form argument. From the class it is already known how to parse it which is not the case for a list. Then a data frame is also kind of both - column major (its list origins) and row major (in the vctrs sense). So, it only makes sense (and is more convenient) to accept both as input form for a data frame.

Your examples already work nicely:

``` r
library(conflicted)
library(dplyr)
library(tibblify)

tibble(a = 1:2, b = '{"c": 2}') %>% 
  dplyr::mutate(b = purrr::map(b, jsonlite::fromJSON, simplifyDataFrame = FALSE)) %>% 
  tibblify(
    spec_df(
      tib_dbl("a"),
      tib_row("b", tib_int("c")),
    )
  )
#> # A tibble: 2 × 2
#>       a   b$c
#>   <dbl> <int>
#> 1     1     2
#> 2     2     2

tibble(a = 1, b = '[{"c": 2}, {"c": 3}]') %>% 
  dplyr::mutate(b = purrr::map(b, jsonlite::fromJSON, simplifyDataFrame = FALSE)) %>% 
  tibblify(
    spec_df(
      tib_dbl("a"),
      tib_df("b", tib_int("c")),
    )
  )
#> # A tibble: 1 × 2
#>       a                  b
#>   <dbl> <list<tibble[,1]>>
#> 1     1            [2 × 1]
```

<sup>Created on 2022-07-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Of course you need to use `tib_row()` in one case and `tib_df()` in the other but this makes sense as the output form is quite different.
