### ISSUE TITLE
Default value for key arguments in tib_*()?

### ISSUE THREAD

**Issue by krlmlr** [mgirlich/tibblify#67]
Should we support the following:

``` r
library(tibblify)

spec_df(
  a = tib_chr()
)
#> Error in tib_scalar_impl(key, ptype = character(), required = required, : argument "key" is missing, with no default

# Desired semantics:
spec_df(
  a = tib_chr("a")
)
#> spec_df(
#>   a = tib_chr("a")
#> )
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mgirlich** [comment]
I started the other way round. You specify the path and `spec_df()` automatically creates the name:

```r
spec_df(
  tib_chr("a")
)
```

But I think always having a name makes the spec nicer to read. Your idea always has a name but otherwise I think it does not really make sense. At leas `tib_chr()` on its own does not seem useful to me. Only in the context of `spec_df()` it would be valid.

**Comment by krlmlr** [comment]
#98 is a more recent take.
